// model package 
package com.buyfy.model;

//Import Files Used In this Program
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/*
 * Address Entity
 */
@Entity
@Table(name = "ADDRESS")
public class Address implements Serializable
{
	// serial version uid
	private static final long serialVersionUID = 881797314942947387L;
	
	/* **** Address Attributes ***** */
	/* Address Primary Key (address_id)
	 * address id will be Generated by Sequence Strategy  ADDRESS_SEQ_GEN
	 * */
	@Id
	@Column(name = "address_id")
    @GeneratedValue (strategy= GenerationType.SEQUENCE, generator="ADDRESS_SEQ_GEN")
    @SequenceGenerator(name = "ADDRESS_SEQ_GEN", allocationSize=1, sequenceName = "ADDRESS_SEQ_GEN")
	private long id;
	
	
	//variable for address line 1
	@Column(name="Address_Line1")
	private String addressLine1;
	
	//variable for address line 2
	@Column(name="Address_Line2")
	private String addressLine2;
	
	//variable for city
	@Column(name="City")
	private String city;
	
	//variable for State
	@Column(name="State")
	private String state;
	
	//variable for postalcode
	@Column(name="PostalCode")
	private String postalCode;
	
	//variable for country
	@Column(name="Country")
	private String country;
	
	// No Argument Address Constructor
	public Address() {}

	// Parameterized Address Constructor
	public Address(String addressLine1, 
			String addressLine2, String city, String state,
			String postalCode, String country) 
	{
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
		this.country = country;
	}

	/*
	 * Address Getters and Setters 
	 */
	// getter for addressLine1
	public String getAddressLine1() {
		return addressLine1;
	}

	// setter for addressLine1
	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	// getter for addressLine2
	public String getAddressLine2() {
		return addressLine2;
	}

	// setter for addressLine2
	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	// getter for city
	public String getCity() {
		return city;
	}

	// setter for city
	public void setCity(String city) {
		this.city = city;
	}

	// getter for state
	public String getState() {
		return state;
	}

	// setter for state
	public void setState(String state) {
		this.state = state;
	}

	// getter for postalCode
	public String getPostalCode() {
		return postalCode;
	}

	// setter for postalCode
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	// getter for country
	public String getCountry() {
		return country;
	}

	// setter for country
	public void setCountry(String country) {
		this.country = country;
	}

	/*
	 * Overriding toString for Address
	 */
	@Override
	public String toString() {
		return "Address [addressLine1=" + addressLine1 + ", addressLine2=" + addressLine2 + ", city=" + city
				+ ", state=" + state + ", postalCode=" + postalCode + ", country=" + country + "]";
	}
}
