// model package 
package com.buyfy.model;

// Import Files Used In this Program
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/*
 * Cart Entity
 * This will be use to store user cart details
 * If user logs out their cart details will be
 * saved in the database.
 */
@Entity
@Table(name = "cart")
public class Cart implements Serializable{
	// serial version uid
	private static final long serialVersionUID = -60870822764595676L;

	/* **** Cart Attributes ***** */
	/* Cart Primary Key (CART_ID)
	 * Cart Id will be Generated by Sequence Strategy  CART_SQE_GEN
	 * */
	@Id
	@Column(name = "CART_ID")
    @GeneratedValue (strategy= GenerationType.SEQUENCE, generator="CART_SEQ_GEN")
    @SequenceGenerator(name = "CART_SEQ_GEN", allocationSize=1, sequenceName = "CART_SEQ_GEN")
	private long id;
	
	/* Products will be Set ProductQuantity for storing
	 * Product and their corresponding quantity for
	 * Cart and Orders related to users.
	 */
	@OneToMany(cascade= CascadeType.ALL, fetch=FetchType.EAGER)
	@JoinColumn(name="Cart_ProductQuantity_ID")
	private Set<ProductQuantity> products = new HashSet<>();

	// No Argument Cart Constructor
	public Cart() {}
	
	// Parameterized Cart Constructor
	public Cart(long id, Set<ProductQuantity> products) {
		super();
		this.id = id;
		this.products = products;
	}

	/*
	 * Cart Getters and Setters 
	 */
	// getter for id
	public long getId() {
		return id;
	}

	// setter for id
	public void setId(long id) {
		this.id = id;
	}

	// getter for Set<ProductQuantity>
	public Set<ProductQuantity> getProducts() {
		return products;
	}

	// setter for Set<ProductQuantity>
	public void setProducts(Set<ProductQuantity> products) {
		this.products = products;
	}

	/*
	 * Overriding toString for Cart
	 */
	@Override
	public String toString() {
		return "Cart [id=" + id + "]";
	}
}