// model package
package com.buyfy.model;

//Import Files Used In this Program
import java.io.Serializable;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/*
 * Categories Entity
 */
@Entity
@Table(name = "categories")
public class Category implements Serializable
{
	// serial version uid
	private static final long serialVersionUID = 2419418471341326854L;
	
	/* **** Category Attributes ***** */
	/* Category Primary Key (Category_ID)
	 * Category Id will be Generated by Sequence Strategy  CATEGORY_SQE_GEN
	 * */
	@Id
	@Column(name="Category_ID") 
	@GeneratedValue (strategy= GenerationType.SEQUENCE, generator="CATEGORY_SEQ_GEN") 
	@SequenceGenerator(name = "CATEGORY_SEQ_GEN", allocationSize=1 , sequenceName = "CATEGORY_SEQ_GEN")
	private long id;
	
	//variable for category Type
	@Column(name="Category_Type", unique=true)
	private String categoryType;
	
	/* Products will be Set Product for storing
	 * Product category
	 */
	@OneToMany(mappedBy = "category", fetch=FetchType.EAGER)
	private Set<Product> products;

	// No Argument Category Constructor
	public Category()  {}

	// Parameterized Category Constructor
	public Category(String categoryType, String categorySubtype) {
		super();
		this.categoryType = categoryType;
	}
	
	/*
	 * Category Getters and Setters 
	 */
	// getter for id
	public long getId() {
		return id;
	}
	
	// setter for id
	public void setId(long id) {
		this.id = id;
	}
	
	// getter for Category Type
	public String getCategoryType() {
		return categoryType;
	}

	// setter for Category Type
	public void setCategoryType(String categoryType) {
		this.categoryType = categoryType;
	}

	// getter for Set<Product>
	public Set<Product> getProducts() {
		return products;
	}

	// setter for Set<Product>
	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	/*
	 * Overriding toString for Category
	 */
	@Override
	public String toString() {
		return "Category [id=" + id + ", categoryType=" + categoryType + "]";
	}
}
