// model package
package com.buyfy.model;

//Import Files Used In this Program
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/*
 * Feedback Entity
 */
@Entity
@Table(name = "feedbacks")
public class Feedback
{
	/* **** Feedback Attributes ***** */
	/* Feedback Primary Key (FEEDBACK_ID)
	 * Feedback Id will be Generated by Sequence Strategy  FEEDBACK_SQE_GEN
	 * */
	@Id 
	@Column(name="Feedback_ID") 
	@GeneratedValue (strategy= GenerationType.SEQUENCE, generator="FEEDBACK_SEQ_GEN") 
	@SequenceGenerator(name = "FEEDBACK_SEQ_GEN", allocationSize=1 , sequenceName = "FEEDBACK_SEQ_GEN") 									
	private long id;
	
	//variable for Description Type
	@Column(name="Description")
	private String desc;

	//variable for user name
	@Column(name="name")
	private String name;

	//variable for user mail
	@Column(name="email")
	private String email;
	
	//variable for Feedback Time
	@Column(name = "Feedback_Time")
	@Temporal(TemporalType.TIMESTAMP)
	private Date timeStamp;
	
	// No Argument Feedback Constructor
	public Feedback() {}

	// Parameterized Feedback Constructor
	public Feedback(long id, String desc, String name, String email, Date timeStamp) {
		super();
		this.id = id;
		this.desc = desc;
		this.name = name;
		this.email = email;
		this.timeStamp = timeStamp;
	}

	/*
	 * Feedback Getters and Setters 
	 */
	// getter for id
	public long getId() {
		return id;
	}

	// setter for id
	public void setId(long id) {
		this.id = id;
	}

	// getter for description
	public String getDesc() {
		return desc;
	}

	// setter for description
	public void setDesc(String desc) {
		this.desc = desc;
	}

	// getter for name
	public String getName() {
		return name;
	}

	// setter for name
	public void setName(String name) {
		this.name = name;
	}

	// getter for email
	public String getEmail() {
		return email;
	}

	// setter for email
	public void setEmail(String email) {
		this.email = email;
	}

	// getter for feedback time
	public Date getTimeStamp() {
		return timeStamp;
	}

	// setter for feedback time
	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	/*
	 * Overriding toString for Feedback
	 */
	@Override
	public String toString() {
		return "Feedback [id=" + id + ", desc=" + desc + ", name=" + name + ", email=" + email + ", timeStamp="
				+ timeStamp + "]";
	}


}