// model package 
package com.buyfy.model;

//Import Files Used In this Program
import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/*
 * Order Entity
 * This will use to store user order details which
 * saved in the database.
 */
@Entity
@Table(name = "orders")
public class Order implements Serializable {
	// serial version uid
	private static final long serialVersionUID = -5564276376850546086L;

	/* **** Order Attributes ***** */
	/* Order Primary Key (ORDER_ID)
	 * Order Id will be Generated by Sequence Strategy  ORDER_SQE_GEN
	 * */
	@Id
	@Column(name = "order_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ORDER_SEQ_GEN")
	@SequenceGenerator(name = "ORDER_SEQ_GEN", allocationSize = 1, sequenceName = "ORDER_SEQ_GEN")
	private long id;
	
	/* Products will be Set ProductQuantity for storing
	 * Product and their corresponding quantity for
	 * Cart and Orders related to users.
	 */
	@OneToMany(cascade = CascadeType.ALL,fetch = FetchType.EAGER)
	@JoinColumn(name = "PRODUCT_ID")
	private Set<ProductQuantity> products;

	
	@ManyToOne(fetch = FetchType.EAGER)
	private User user;

	//variable for total amt.
	@Column(name="total_amt")
	private double amount;
	
	// Billing Details
	
	//variable for user first name
	@Column(name = "First_Name")
	private String firstName;

	//variable for user last name
	@Column(name = "Last_Name")
	private String lastName;

	//variable for user address
	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@JoinColumn(name = "address")
	private Address address;

	//variable for user phone no
	@Column(name = "Phone")
	private String phone;

	// Billing Details End

	//variable for order date
	@Column(name = "Order_Date")
	@Temporal(TemporalType.TIMESTAMP)
	private Date orderDate;

	//variable for sales tax on products
	@Column(name = "SalesTax")
	private double salesTax;

	// Paytm ID
	@Column(name = "Payment_ID")
	private String paytmPaymentID;

	//variable for transac. status
	@Column(name = "Transac_Status")
	private boolean transacStatus;

	//variable for payment date 
	@Column(name = "Payment_Date")
	@Temporal(TemporalType.TIMESTAMP)
	private Date paymentDate;

	//variable for order delivered status
	@Column(name = "Order_Delivered")
	private boolean orderDelivered;

	// No Argument Order Constructor
	public Order() {
	}

	// Parameterized Order Constructor
	public Order(Set<ProductQuantity> products, User user, double amount, String firstName, String lastName,
			Address address, String phone, String paytmPaymentID, Date orderDate, double salesTax,
			boolean transacStatus, Date paymentDate, boolean orderDelivered) {
		super();
		this.products = products;
		this.user = user;
		this.amount = amount;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address = address;
		this.phone = phone;
		this.paytmPaymentID = paytmPaymentID;
		this.orderDate = orderDate;
		this.salesTax = salesTax;
		this.transacStatus = transacStatus;
		this.paymentDate = paymentDate;
		this.orderDelivered = orderDelivered;
	}

	/*
	 * Order Getters and Setters 
	 */
	// getter for id
	public long getId() {
		return id;
	}

	// setter for id
	public void setId(long id) {
		this.id = id;
	}
	
	// getter for Set<ProductQuantity>
	public Set<ProductQuantity> getProducts() {
		return products;
	}

	// setter for Set<ProductQuantity>
	public void setProducts(Set<ProductQuantity> products) {
		this.products = products;
	}

	// getter for user
	public User getUser() {
		return user;
	}

	// setter for user
	public void setUser(User user) {
		this.user = user;
	}

	// getter for amount
	public double getAmount() {
		return amount;
	}

	// setter for amount
	public void setAmount(double amount) {
		this.amount = amount;
	}

	// getter for first name
	public String getFirstName() {
		return firstName;
	}

	// setter for first name
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	// getter for last name
	public String getLastName() {
		return lastName;
	}

	// setter for last name
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	// getter for address
	public Address getAddress() {
		return address;
	}

	// setter for address
	public void setAddress(Address address) {
		this.address = address;
	}

	// getter for phone no
	public String getPhone() {
		return phone;
	}

	// setter for phone no
	public void setPhone(String phone) {
		this.phone = phone;
	}

	// getter for order date
	public Date getOrderDate() {
		return orderDate;
	}

	// setter for order date
	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	// getter for sales tax
	public double getSalesTax() {
		return salesTax;
	}

	// setter for sales tax
	public void setSalesTax(double salesTax) {
		this.salesTax = salesTax;
	}

	// getter for payment id
	public String getPaytmPaymentID() {
		return paytmPaymentID;
	}

	// setter for payment id
	public void setPaytmPaymentID(String paytmPaymentID) {
		this.paytmPaymentID = paytmPaymentID;
	}

	// getter for tansc. status
	public boolean isTransacStatus() {
		return transacStatus;
	}

	// setter for tansc. status
	public void setTransacStatus(boolean transacStatus) {
		this.transacStatus = transacStatus;
	}

	// getter for payment date
	public Date getPaymentDate() {
		return paymentDate;
	}
	
	// setter for payment date
	public void setPaymentDate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	// getter for order delivered status
	public boolean isOrderDelivered() {
		return orderDelivered;
	}

	// setter for order delivered status
	public void setOrderDelivered(boolean orderDelivered) {
		this.orderDelivered = orderDelivered;
	}

	/*
	 * Overriding toString for Order
	 */
	@Override
	public String toString() {
		return "Orders [id=" + id +", user_id="+user.getId()+",First Name="+ firstName+" products=" + products + ", paymentID=" + paytmPaymentID + ", orderDate=" + orderDate
				+ ", salesTax=" + salesTax + ", transacStatus=" + transacStatus + ", paymentDate=" + paymentDate
				+ ", orderDelivered=" + orderDelivered + "]";
	}
}
