// model package 
package com.buyfy.model;

//Import Files Used In this Program
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/*
 * Product Review Entity
 * This will use to store Product Reviews.
 */
@Entity
@Table(name = "PRODUCT_REVIEWS")
public class ProductReview implements Serializable
{
	// serial version uid
	private static final long serialVersionUID = -8631320086784402597L;
	
	/* **** REVIEW Attributes ***** */
	/* REVIEW Primary Key (REVIEW_ID)
	 * REVIEW Id will be Generated by Sequence Strategy  REVIEW_SQE_GEN
	 * */
	@Id 
	@Column(name="REVIEW_ID") 
	@GeneratedValue (strategy= GenerationType.SEQUENCE, generator="ProdReview_SEQ_GEN") 
	@SequenceGenerator(name = "ProdReview_SEQ_GEN", allocationSize=1 , sequenceName = "ProdReview_SEQ_GEN")
	private long id;

	//variable for product reviewer
	@Column(name = "Product_Reviewer")
	private String reviewer;

	//variable for product review
	@Column(name="Review")
	private String review;
	
	// No Argument ProductReview Constructor
	public ProductReview()  {}

	// Parameterized ProductReview Constructor
	public ProductReview(String reviewer, String review) {
		super();
		this.reviewer = reviewer;
		this.review = review;
	}

	/*
	 * ProductReview Getters and Setters 
	 */
	// getter for id
	public long getId() {
		return id;
	}

	// setter for id
	public void setId(long id) {
		this.id = id;
	}

	// getter for reviewer
	public String getReviewer() {
		return reviewer;
	}

	// setter for reviewer
	public void setReviewer(String reviewer) {
		this.reviewer = reviewer;
	}

	// getter for review
	public String getReview() {
		return review;
	}

	// setter for review
	public void setReview(String review) {
		this.review = review;
	}

	// getter for Serialversionuid
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/*
	 * Overriding toString for Product Reviews
	 */
	@Override
	public String toString() {
		return "ProductReviews [id=" + id + ", reviewer=" + reviewer + ", review=" + review + "]";
	}
}
